version: '3.7'

services:
  nginx:
    container_name: nginx_container
    build: Nginx
    ports:
      - 80:80
    restart: unless-stopped
    
  api:
    container_name: webApi_container
    build: WebApi
    restart: unless-stopped
